# Basic options
title: No Swim Zone
author: Sean Tuck
description: Website for the No Swim Zone podcast

# Build settings
markdown: kramdown
theme: minima
plugins:
  - audioinfo

# License config
license: GNU GPLv3
license_url: https://www.gnu.org/licenses/gpl-3.0.html

# Site content tags
explicit: "no"
